import React,{useEffect,useMemo,useRef,useState,Suspense} from 'react';
import ReactDOM from 'react-dom/client';
import {Canvas,useFrame} from '@react-three/fiber';
import {Sky,OrbitControls} from '@react-three/drei';
import {Physics,RigidBody,CapsuleCollider,CuboidCollider} from '@react-three/rapier';
import * as THREE from 'three';
import './styles.css';
import { useTexture } from '@react-three/drei';


const EVID=[11.7,.5,4], NPCS={cleaner:[14,.9,.8],patrol:[17,.9,18],news:[9.5,.9,-59]};
const DIALOG={cleaner:['清潔工','我今朝返工時見到個紙盒放喺行人路邊。','cleaner'],patrol:['巡警','現場已封鎖。先從外圍觀察紙盒、馬路同附近出入口。','patrol'],news:['報販／街坊綜合角色','朝早呢段路通常已經開始多人；大型物件搬運理應較易被留意。','visibility']};
const saveKey='hk-case-ch01-deploy-preview-v1';
function useSave(state){useEffect(()=>{const t=setTimeout(()=>localStorage.setItem(saveKey,JSON.stringify(state)),200);return()=>clearTimeout(t)},[state])}

function City(){
 const asphalt=useTexture('./textures/asphalt.svg'); const concrete=useTexture('./textures/concrete.svg'); const plaster=useTexture('./textures/plaster.svg');
 for(const t of [asphalt,concrete,plaster]){t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;}
 asphalt.repeat.set(8,24);concrete.repeat.set(5,22);plaster.repeat.set(2,2);
 const b=[]; for(let i=0;i<7;i++) b.push(<mesh key={i} position={[64,8+i*30-90,10+(i%3)*3]}><boxGeometry args={[28,24,20+(i%3)*6]}/><meshStandardMaterial map={plaster} color={i%2?'#b0a38f':'#d1c0a5'} roughness={.94}/></mesh>);
 return <group>
  <mesh position={[0,-.2,0]} receiveShadow><boxGeometry args={[250,.4,300]}/><meshStandardMaterial map={concrete} color="#d0c5b4" roughness={.96}/></mesh>
  <mesh position={[25,.02,0]} receiveShadow><boxGeometry args={[24,.12,230]}/><meshStandardMaterial map={asphalt} color="#a5a29a" roughness={.92}/></mesh>
  <mesh position={[-57,.03,5]}><boxGeometry args={[95,.12,210]}/><meshStandardMaterial color="#526b4f"/></mesh>
  <mesh position={[-7,.6,5]}><boxGeometry args={[1.4,1.2,215]}/><meshStandardMaterial color="#9b9585"/></mesh>
  {b}
  {[20.5,29.5].map(x=><mesh key={x} position={[x,.13,-3]}><boxGeometry args={[.12,.06,190]}/><meshStandardMaterial color="#777" metalness={.4}/></mesh>)}
  <mesh position={[11.7,.5,4]}><boxGeometry args={[1.2,.9,.85]}/><meshStandardMaterial color="#8b6744"/></mesh>
  {Object.entries(NPCS).map(([k,p])=><group key={k} position={p}><mesh><capsuleGeometry args={[.25,.95,4,8]}/><meshStandardMaterial color={k==='patrol'?'#475769':'#566f85'}/></mesh><mesh position={[0,.8,0]}><sphereGeometry args={[.19,12,12]}/><meshStandardMaterial color="#b49a7a"/></mesh></group>)}
  {[[-1,42],[-1,3],[-1,-38],[-1,-74]].map((p,i)=><group key={i} position={[p[0],0,p[1]]}><mesh position={[0,2,0]}><cylinderGeometry args={[.22,.22,4,8]}/><meshStandardMaterial color="#5c4534"/></mesh><mesh position={[0,5,0]}><sphereGeometry args={[2.3,10,8]}/><meshStandardMaterial color="#526a47"/></mesh></group>)}
 </group>
}
function Tram(){const r=useRef();useFrame(({clock})=>{if(r.current)r.current.position.z=((clock.elapsedTime*2.6)%118)-59});return <group ref={r} position={[25,1.8,0]}><mesh castShadow><boxGeometry args={[2,3.4,8.5]}/><meshStandardMaterial color="#315a3d"/></mesh><mesh position={[0,1.9,0]}><boxGeometry args={[1.9,1.7,8]}/><meshStandardMaterial color="#315a3d"/></mesh></group>}
function Colliders(){return <RigidBody type="fixed" colliders={false}><CuboidCollider args={[125,.15,150]} position={[0,-.15,0]}/><CuboidCollider args={[.8,.8,107.5]} position={[-7,.7,5]}/>{[70,40,10,-20,-50,-80].map((z,i)=><CuboidCollider key={z} args={[14,12,12]} position={[64,12,z]}/>)}</RigidBody>}
function Player({onPos,enabled=true,initial=[32,1.1,-112]}){const body=useRef(),keys=useRef({}),yaw=useRef(0),pitch=useRef(0);useEffect(()=>{const d=e=>keys.current[e.code]=true,u=e=>keys.current[e.code]=false,m=e=>{if(document.pointerLockElement&&enabled){yaw.current-=e.movementX*.0022;pitch.current=THREE.MathUtils.clamp(pitch.current-e.movementY*.0019,-1.25,1.25)}};addEventListener('keydown',d);addEventListener('keyup',u);addEventListener('mousemove',m);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u);removeEventListener('mousemove',m)}},[enabled]);useFrame(({camera})=>{if(!body.current)return;const p=body.current.translation(),k=keys.current;const f=enabled?+!!k.KeyW-+!!k.KeyS:0,s=enabled?+!!k.KeyD-+!!k.KeyA:0,spd=k.ShiftLeft?8:5.2;const v=new THREE.Vector3(s,0,-f);if(v.lengthSq()){v.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw.current);const l=body.current.linvel();body.current.setLinvel({x:v.x*spd,y:l.y,z:v.z*spd},true)}else{const l=body.current.linvel();body.current.setLinvel({x:0,y:l.y,z:0},true)}camera.position.set(p.x,p.y+1.48,p.z);camera.rotation.set(pitch.current,yaw.current,0,'YXZ');onPos([p.x,p.y,p.z])});return <RigidBody ref={body} colliders={false} enabledRotations={[false,false,false]} position={initial} linearDamping={8}><CapsuleCollider args={[.55,.34]} position={[0,.85,0]}/></RigidBody>}
function Inspect({close,record}){return <div className="modal"><div className="inspect"><div className="inspect3d"><Canvas camera={{position:[4,2.4,5],fov:45}}><ambientLight intensity={1.3}/><directionalLight position={[3,5,2]} intensity={2}/><mesh rotation={[.1,-.4,0]}><boxGeometry args={[2.2,1.55,1.65]}/><meshStandardMaterial color="#8f6f49" roughness={.95}/></mesh><OrbitControls enablePan={false}/></Canvas></div><aside><span>證物 E01</span><h2>紙盒</h2><p>拖動旋轉、滾輪縮放。記錄觀察，不直接判定案件結論。</p><button onClick={()=>record('box_rope')}>記錄：外部綁繩痕跡</button><button onClick={()=>record('box_condition')}>記錄：搬運／磨損痕跡</button><button className="ghost" onClick={close}>返回現場</button></aside></div></div>}
function App(){const saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(saveKey)||'{}')}catch{return{}}},[]);const [load,setLoad]=useState(true),[entered,setEntered]=useState(false),[pos,setPos]=useState(saved.pos||[32,1,-112]),[clues,setClues]=useState(saved.clues||[]),[near,setNear]=useState(null),[talk,setTalk]=useState(null),[inspect,setInspect]=useState(false),[book,setBook]=useState(false),[evening,setEvening]=useState(saved.evening||false),[complete,setComplete]=useState(saved.complete||false);useSave({pos,clues,evening,complete});useEffect(()=>{const t=setTimeout(()=>setLoad(false),1200);return()=>clearTimeout(t)},[]);const add=c=>setClues(x=>x.includes(c)?x:[...x,c]);const trigger=new THREE.Vector3(...pos).distanceTo(new THREE.Vector3(...EVID))<7;useEffect(()=>{const p=new THREE.Vector3(...pos);const n=Object.entries(NPCS).map(([id,v])=>[id,p.distanceTo(new THREE.Vector3(...v))]).sort((a,b)=>a[1]-b[1])[0];setNear(n&&n[1]<3.2?n[0]:null)},[pos]);const firstReady=['cleaner','visibility'].every(x=>clues.includes(x))&&['box_rope','box_condition'].some(x=>clues.includes(x));const secondReady=clues.includes('identity')&&clues.includes('contact')&&evening&&clues.includes('tram')&&clues.includes('gap');const controls=entered&&!talk&&!inspect&&!book&&!complete;
 return <main>{(load||!entered)&&<div className="loading"><div><small>HONG KONG CASE ARCHIVE</small><h1>CASE 001</h1><p>跑馬地／1974</p><div className="bar"><i/></div><button disabled={load} onClick={()=>setEntered(true)}>{load?'重建中…':'進入案件'}</button></div></div>}{complete&&<div className="loading"><div className="complete"><small>CHAPTER 01 COMPLETE</small><h1>調查仍未結束</h1><p>你已建立兩個工作假說：紙盒曾被搬運；總站之後的確切路線仍屬未知。</p><button onClick={()=>setBook(true)}>查看案件簿</button></div></div>}
 <Canvas shadows camera={{position:[32,2.6,-112],fov:62}} onPointerDown={e=>controls&&e.gl.domElement.requestPointerLock?.()}><color attach="background" args={[evening?'#6c6257':'#c8c0ad']}/><fog attach="fog" args={[evening?'#6c6257':'#c8c0ad',45,180]}/><ambientLight intensity={evening?.42:.7}/><hemisphereLight args={['#e7e0d4','#4b5448',evening?.4:.65]}/><directionalLight castShadow shadow-mapSize-width={2048} shadow-mapSize-height={2048} position={evening?[-30,18,-20]:[40,70,-30]} intensity={evening?1.3:2.3} color={evening?'#d49b71':'#fff'} /><Sky sunPosition={evening?[-.8,.12,-.5]:[.2,.45,.15]}/><Physics gravity={[0,-9.81,0]}><City/><Tram/><Colliders/><Player enabled={controls} initial={saved.pos||[32,1.1,-112]} onPos={setPos}/></Physics></Canvas>
 <section className="hud"><small>HONG KONG CASE ARCHIVE</small><b>CASE 001 / 跑馬地 / 1974</b><p>{evening?'1974-12-16 傍晚重建：確認最後可信位置':'1974-12-17 現場：前往異常人群與紙盒位置'}</p><div className="progress"><i style={{width:`${Math.min(100,(clues.length/7)*100)}%`}}/></div></section><div className="tools"><button onClick={()=>setBook(true)}>案件簿</button>{firstReady&&!evening&&<button onClick={()=>setEvening(true)}>傍晚重建</button>}</div><div className="help">WASD 移動 · Shift 快走 · 滑鼠視角</div>{near&&!talk&&<button className="talk" onClick={()=>setTalk(near)}>與 {DIALOG[near][0]} 對話</button>}{trigger&&!inspect&&!evening&&<button className="prompt" onClick={()=>setInspect(true)}>檢查紙盒</button>}
 {talk&&<div className="dialog"><small>{DIALOG[talk][0]}</small><p>{DIALOG[talk][1]}</p><button onClick={()=>{add(DIALOG[talk][2]);setTalk(null)}}>記錄口供</button></div>}{inspect&&<Inspect close={()=>setInspect(false)} record={c=>add(c)}/>} {evening&&<div className="recon"><b>RECONSTRUCTION / 1974-12-16</b><button onClick={()=>add('tram')}>{clues.includes('tram')?'✓ 電車總站節點':'確認電車總站節點'}</button><button onClick={()=>add('gap')}>{clues.includes('gap')?'✓ Unknown 路段':'標示總站後 Unknown'}</button></div>}
 {book&&<div className="modal"><div className="case"><header><div><small>CASEBOOK</small><h2>跑馬地檔案：紙盒</h2></div><button onClick={()=>setBook(false)}>關閉</button></header><div className="docs"><button onClick={()=>add('identity')} className={clues.includes('identity')?'done':''}>D01 身份／失蹤紀錄</button><button onClick={()=>add('contact')} className={clues.includes('contact')?'done':''}>D02 最後聯絡</button></div><h3>已記錄線索</h3><ul>{clues.map(c=><li key={c}>{c}</li>)}</ul><h3>第一推理</h3><p>紙盒曾被搬運，而棄置時間／方式仍需調查。</p><button disabled={!firstReady} className={firstReady?'ok':''}>工作假說 {firstReady?'已成立':'未解鎖'}</button><h3>第二推理</h3><p>電車總站附近可作最後可信空間節點；之後應保留為 Unknown。</p><button disabled={!secondReady} className={secondReady?'ok':''} onClick={()=>{if(secondReady){setComplete(true);setBook(false)}}}>提交第二推理</button></div></div>}
 </main>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
